version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/smartesp-studio-frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/smartesp-studio"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
